// src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { NavbarComponent } from './components/navbar/navbar.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, CommonModule, NavbarComponent],
  templateUrl: './app.component.html',
})
export class AppComponent {}

<div [ngClass]="{ dark: navbar.isDarkMode() }" class="flex min-h-screen w-full">
  <div
    class="flex min-h-screen w-full bg-neutral-50 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-50">
    <app-navbar #navbar />
    <main class="flex-1 p-8">
      <router-outlet />
    </main>
  </div>
</div>

// React/src/App.tsx
import { Navbar } from "./components/Navbar.tsx";

function App() {

  return (
    <>
      <div className="flex min-h-screen w-full">
        <div
          className="flex min-h-screen w-full bg-neutral-100 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-50">
          <Navbar></Navbar>
        </div>
      </div>
    </>
  );
}

export default App;
