// Angular/src/app/components/navbar/navbar.component.ts
import { Component, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SvgIconComponent } from 'angular-svg-icon';

type Theme = 'light' | 'dark' | 'system';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, SvgIconComponent],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent implements OnInit {
  private static readonly LOCALSTORAGE_KEY = 'theme';

  readonly siteName = 'Vault8';
  readonly isDarkMode = signal(false);
  readonly currentTheme = signal<Theme>('system');
  readonly isDropdownOpen = signal(false);
  readonly themes: Theme[] = ['light', 'dark', 'system'];

  private systemThemeMedia = window.matchMedia('(prefers-color-scheme: dark)');

  constructor() {
    const savedTheme = this.getSavedTheme();
    this.currentTheme.set(savedTheme);
    this.updateTheme();
  }

  ngOnInit() {
    this.systemThemeMedia.addEventListener('change', () => {
      if (this.currentTheme() === 'system') {
        this.updateTheme();
      }
    });
  }

  private getSavedTheme(): Theme {
    try {
      const savedTheme = localStorage.getItem(NavbarComponent.LOCALSTORAGE_KEY);
      return savedTheme === 'light' ||
        savedTheme === 'dark' ||
        savedTheme === 'system'
        ? (savedTheme as Theme)
        : 'system';
    } catch {
      return 'system';
    }
  }

  private saveTheme(theme: Theme) {
    try {
      localStorage.setItem(NavbarComponent.LOCALSTORAGE_KEY, theme);
    } catch (error) {
      console.error('Error saving theme:', error);
    }
  }

  private updateTheme() {
    const theme = this.currentTheme();
    if (theme === 'system') {
      this.isDarkMode.set(this.systemThemeMedia.matches);
    } else {
      this.isDarkMode.set(theme === 'dark');
    }
  }

  setTheme(theme: Theme) {
    this.currentTheme.set(theme);
    this.isDropdownOpen.set(false);
    this.saveTheme(theme);
    this.updateTheme();
  }

  toggleDropdown() {
    this.isDropdownOpen.update(v => !v);
  }

  getThemeText(): string {
    return this.currentTheme() || 'system';
  }

  getThemeIcon(theme: Theme): string {
    let iconName = 'system';

    if (theme === 'light') {
      iconName = 'sun';
    } else if (theme === 'dark') {
      iconName = 'moon';
    }

    return `assets/icon-${iconName}.svg`;
  }
}

<nav
  class="absolute flex h-16 w-full justify-between border-b border-neutral-200 bg-white px-4 dark:border-neutral-800 dark:bg-neutral-900">
  <!-- Left section with logo and title -->
  <div class="flex items-center gap-4">
    <img src="assets/logo-vault8.png" alt="Logo" class="h-12" />
    <h1 class="m-0 text-xl font-semibold text-neutral-900 dark:text-neutral-50">
      {{ siteName }}
    </h1>
  </div>

  <!-- Theme switcher dropdown -->
  <div class="relative flex items-center">
    <button (click)="toggleDropdown()" class="flex items-center p-3">
      <span class="mr-2">
        <svg-icon
          [src]="getThemeIcon(currentTheme())"
          [svgStyle]="{ 'width.px': 24 }"></svg-icon>
      </span>
      <span class="flex items-center capitalize">
        {{ currentTheme() }}
      </span>
    </button>

    <!-- Dropdown menu -->
    @if (isDropdownOpen()) {
      <div
        class="absolute right-0 top-full mt-2 w-48 rounded-lg border border-neutral-200 bg-white shadow-lg dark:border-neutral-700 dark:bg-neutral-800">
        <div class="p-1">
          @for (theme of themes; track theme) {
            <button
              (click)="setTheme(theme)"
              class="flex w-full items-center gap-3 rounded p-2 text-neutral-700 hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-700"
              [class.bg-neutral-100]="currentTheme() === theme"
              [class.dark:bg-neutral-700]="currentTheme() === theme">
              <span class="mr-2">
                <svg-icon
                  [src]="getThemeIcon(theme)"
                  [svgStyle]="{ 'width.px': 24 }"></svg-icon>
              </span>
              <span class="capitalize">{{ theme }}</span>
            </button>
          }
        </div>
      </div>
    }
  </div>
</nav>

// React/src/components/Navbar.tsx
import vault8Logo from "../assets/logo-vault8.png";
import iconMoon from "../assets/icon-moon.svg";
import iconSun from "../assets/icon-sun.svg";
import iconSystem from "../assets/icon-system.svg";
import { useState } from "react";

interface Theme {
  name: string;
  className: string;
  icon: string;
}

const themes: Theme[] = [
  { name: "Light", className: "light", icon: iconSun },
  { name: "Dark", className: "dark", icon: iconMoon },
  { name: "System", className: "system", icon: iconSystem }
];

export const Navbar: React.FC = () => {
  const [currentTheme, setCurrentTheme] = useState<Theme>(themes[2]);
  const [siteName] = useState("Vault8");
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  function toggleDropdown() {
    setIsDropdownOpen(!isDropdownOpen);
  }

  function updateCurrentTheme(theme: Theme) {
    setCurrentTheme(theme);
    setIsDropdownOpen(false);
    console.log(`🩷Bijoya - Navbar.tsx > 31`);
  }

  function renderDropdown() {
    if (isDropdownOpen) {
      return (<div
        className="absolute right-0 top-full mt-2 w-48 rounded-lg border border-neutral-200 bg-white shadow-lg dark:border-neutral-700 dark:bg-neutral-800">
        <div className="p-1">
          {dropdownButtons()}
        </div>
      </div>);
    }

    return null;
  }

  function dropdownButtons() {
    return themes.map(theme =>
      (
        <button
          className="flex w-full items-center gap-3 rounded p-2 text-neutral-700 hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-700"
          key={theme.name}
          onClick={() => updateCurrentTheme(theme)}
        >
          <span className="mr-2">
            <img src={theme.icon} alt="Current theme" className="h-6" />
          </span>
          <span className="capitalize">{theme.name}</span>
        </button>
      ));
  }

  return (
    <>
      <nav
        className="absolute flex h-16 w-full justify-between border-b border-neutral-200 bg-white px-4 dark:border-neutral-800 dark:bg-neutral-900">
        {/*Left section with logo and title*/}
        <div className="flex items-center gap-4">
          <img src={vault8Logo} alt="Logo" className="h-12" />
          <h1 className="m-0 text-xl font-semibold text-neutral-900 dark:text-neutral-50">
            {siteName}
          </h1>
        </div>

        {/*Theme switcher dropdown*/}
        <div onClick={toggleDropdown} className="relative flex items-center">
          <button className="flex items-center p-3">
        <span className="mr-2">
          <img src={currentTheme.icon} alt="Current theme" className="h-6" />
      </span>
            <span className="flex items-center capitalize">
              {currentTheme.name}
            </span>
          </button>

          {/*Dropdown menu*/}
          {renderDropdown()}
        </div>
      </nav>
    </>
  );
};
